name: graduation_project
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.7
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  toast: ^0.1.5
  fluttertoast: ^7.1.6
  dio:



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/imgs/

 
 
